### ISSUE TITLE
Should add reflection based methods, instead of using generic

### ISSUE THREAD

**Issue by gdyrrahitis** [sextondjc/Drapper#4]
Proposal is to add reflection methods as well, overloading the generic ones.
For example, there is the `IDbCommander.Query<T>` method. Should add a `Query(Type type)` overload as well, in order to generate results by type.

This can be particularly helpful in situations where a `Type` is provided dynamically.
Example:

```
private IDbCommander _commander;
private object _result;

public void SetResultOfType(Type type)
{
    // Result of 'Query' should be of the type provided
   // Alternative to _commander.Query<T>() which requires a strongly typed generic argument
    _result = _commander.Query(resultType: type);
}
```

**Comment by sextondjc** [comment]
Uh... Not quite sure of the use case here. Do you have a more comprehensive example please?

**Comment by sextondjc** [comment]
Drapper no longer under active development. Forks welcome for those who'd like to.
